/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.ButtonGroup;

/**
 *
 * @chongkuaile github.com
 */
public class ArithmeticOperator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ArithmeticOperator.class.getName());

    /**
     * Creates new form ArithmeticOperator
     */
    public ArithmeticOperator() {
        initComponents();
        setTitle("Arithmetic Operator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">    

    private void initComponents() {

        Operations = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NumberField1 = new javax.swing.JTextField();
        NumberField2 = new javax.swing.JTextField();
        ComboBases1 = new javax.swing.JComboBox<>();
        ComboBases2 = new javax.swing.JComboBox<>();
        SolveOperationButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ComboBasesAnswer = new javax.swing.JComboBox<>();
        AddButton = new javax.swing.JRadioButton();
        SubtractButton = new javax.swing.JRadioButton();
        MultiplyButton = new javax.swing.JRadioButton();
        DivideButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputArea = new javax.swing.JTextArea();
        ModuloButton = new javax.swing.JRadioButton();
        ExpoButton = new javax.swing.JRadioButton();
        FloorDivideButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter number/s:");

        jLabel2.setText("Enter number/s:");

        NumberField2.addActionListener(this::NumberField2ActionPerformed);

        ComboBases1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binary", "Decimal", "Octal", "Hexadecimal" }));

        ComboBases2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binary", "Decimal", "Octal", "Hexadecimal" }));
        ComboBases2.addActionListener(this::ComboBases2ActionPerformed);

        SolveOperationButton.setText("Solve");
        SolveOperationButton.addActionListener(this::SolveOperationButtonActionPerformed);

        jLabel3.setText("Show answer as:");

        ComboBasesAnswer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binary", "Decimal", "Octal", "Hexadecimal", "All bases" }));

        Operations.add(AddButton);
        AddButton.setText("Add +");
        AddButton.setActionCommand("Add");
        AddButton.addActionListener(this::AddButtonActionPerformed);

        Operations.add(SubtractButton);
        SubtractButton.setText("Subtract -");
        SubtractButton.setActionCommand("Subtract");
        SubtractButton.addActionListener(this::SubtractButtonActionPerformed);

        Operations.add(MultiplyButton);
        MultiplyButton.setText("Multiply ×");
        MultiplyButton.setActionCommand("Multiply");
        MultiplyButton.addActionListener(this::MultiplyButtonActionPerformed);

        Operations.add(DivideButton);
        DivideButton.setText("Divide ÷");
        DivideButton.setToolTipText("");
        DivideButton.setActionCommand("Divide");
        DivideButton.addActionListener(this::DivideButtonActionPerformed);

        OutputArea.setEditable(false);
        OutputArea.setColumns(20);
        OutputArea.setRows(5);
        jScrollPane1.setViewportView(OutputArea);

        Operations.add(ModuloButton);
        ModuloButton.setText("Modulo %");
        ModuloButton.setActionCommand("Modulo");
        ModuloButton.addActionListener(this::ModuloButtonActionPerformed);

        Operations.add(ExpoButton);
        ExpoButton.setText("Exponentation ^");
        ExpoButton.setActionCommand("Expo");
        ExpoButton.addActionListener(this::ExpoButtonActionPerformed);

        Operations.add(FloorDivideButton);
        FloorDivideButton.setText("Floor Division //");
        FloorDivideButton.setActionCommand("FloorDivide");
        FloorDivideButton.addActionListener(this::FloorDivideButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBases1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(SolveOperationButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBasesAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(NumberField2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBases2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubtractButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MultiplyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DivideButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ModuloButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExpoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FloorDivideButton)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBases1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddButton)
                        .addComponent(SubtractButton)
                        .addComponent(MultiplyButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModuloButton)
                    .addComponent(ExpoButton)
                    .addComponent(FloorDivideButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NumberField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBases2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SolveOperationButton)
                    .addComponent(jLabel3)
                    .addComponent(ComboBasesAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                                           

    private void ComboBases2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    }                                         

    private void DivideButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             

    }                                            

    private void NumberField2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void SolveOperationButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        
        try {
            
            // create variables for the number inputs
            String input1 = NumberField1.getText().toUpperCase();
            String input2 = NumberField2.getText().toUpperCase();

            // calls the method and runs it
            
            Operators(input1, input2);
            
        }
        catch (NumberFormatException e) {
            
            OutputArea.setText("Invalid number/s.");
            
        }

        
    }                                                    
    
    private void Operators(String input1, String input2) {
        
        // create base types variables for conversion
        int fromBase1 = convertBase(ComboBases1.getSelectedIndex());
        int fromBase2 = convertBase(ComboBases2.getSelectedIndex());
        int toBase = convertBase(ComboBasesAnswer.getSelectedIndex());
        
        long initial_1 = Long.parseLong(input1, fromBase1);
        long initial_2 = Long.parseLong(input2, fromBase2);
        
        // create index variable for the buttons
        int operator_index;
        String selectedOperation = Operations.getSelection().getActionCommand();
        
        // check the selected operation and assign the index accordingly
        switch (selectedOperation) {
            case "Add":
                operator_index = 0;
                break;
            case "Subtract":
                operator_index = 1;
                break;
            case "Multiply":
                operator_index = 2;
                break;
            case "Divide":
                operator_index = 3;
                break;
            case "Modulo":
                operator_index = 4;
                break;
            case "Expo":
                operator_index = 5;
                break;
            case "FloorDivide":
                operator_index = 6;
                break;
            default:
                operator_index = -1;
        }
        
        // solve
        try {
            double result;

            switch (operator_index) {
                case 0:
                    result = initial_1 + initial_2;
                    break;
                case 1:
                    result = initial_1 - initial_2;
                    break;
                case 2:
                    result = initial_1 * initial_2;
                    break;
                case 3:
                    result = (double) initial_1 / initial_2;
                    break;
                case 4:
                    result = initial_1 % initial_2;
                    break;
                case 5:
                    result = Math.pow(initial_1, initial_2);
                    break;
                case 6:
                    result = Math.floor((double) initial_1 / initial_2);
                    break;
                default:
                    OutputArea.setText("Please select an operation.");
                    return;
            }

            // checks
            if (Double.isInfinite(result) || Double.isNaN(result)) {
                OutputArea.setText("Cannot divide by zero.");
                return;
            }

            // checks if the decimal base has trailing zeroes, and removes it
            String decimalFormatted;
            if (result == Math.floor(result)) {
                // no fractional part — show as whole number
                decimalFormatted = String.format("%.0f", result);
            } else {
                // has decimals — show with precision
                decimalFormatted = String.format("%.15f", result);
            }
            
            // variables for each base result
            // fractionDigits for the decimal digits numbers
            String binary_result = "Binary: (" + toBaseString(result, 2, 16) + ")₂";
            String decimal_result = "Decimal: " + decimalFormatted;
            String octal_result = "Octal: (" + toBaseString(result, 8, 18) + ")₈";
            String hexadecimal_result = "Hexadecimal: (" + toBaseString(result, 16, 18) + ")₁₆";



            switch (toBase) {
                case 2:
                    OutputArea.setText(binary_result);
                    break;
                case 10:
                    OutputArea.setText(decimal_result);
                    break;
                case 8:
                    OutputArea.setText(octal_result);
                    break;
                case 16:
                    OutputArea.setText(hexadecimal_result);
                    break;
                case 0:
                    String allBasesResult = binary_result + "\n" +
                            decimal_result + "\n" +
                            octal_result + "\n" +
                            hexadecimal_result;
                    OutputArea.setText(allBasesResult);
                    break;
                default:
                    break;
            }

        } catch (ArithmeticException e) {
            OutputArea.setText("Cannot divide by zero.");
        }
    }
    
    private int convertBase(int index) {
        switch (index) {
            case 0:
                return 2; // Binary
            case 1:
                return 10; // Decimal
            case 2:
                return 8; // Octal
            case 3:
                return 16; // Hexadecimal
            default:
                return 0;
        }  
    }

    // method for converting 
    private String toBaseString(double value, int base, int fractionDigits) {
        // handle the integer part with the built-in converter
        long intPart = (long) value;
        double frac = Math.abs(value - intPart);

        StringBuilder sb = new StringBuilder(Long.toString(intPart, base).toUpperCase());

        if (frac > 0) {
            sb.append(".");
            for (int i = 0; i < fractionDigits && frac > 0; i++) {
                frac *= base;                       // shift one digit left
                int digit = (int) frac;             // take the whole-number part
                sb.append(Character.toUpperCase(Character.forDigit(digit, base)));
                frac -= digit;                      // remove that digit, keep going
            }
        }
        return sb.toString();
    }

    private void SubtractButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
    }                                              

    private void MultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
    }
    
    private void ModuloButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void ExpoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void FloorDivideButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ArithmeticOperator().setVisible(true));
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton AddButton;
    private javax.swing.JComboBox<String> ComboBases1;
    private javax.swing.JComboBox<String> ComboBases2;
    private javax.swing.JComboBox<String> ComboBasesAnswer;
    private javax.swing.JRadioButton DivideButton;
    private javax.swing.JRadioButton ExpoButton;
    private javax.swing.JRadioButton FloorDivideButton;
    private javax.swing.JRadioButton ModuloButton;
    private javax.swing.JRadioButton MultiplyButton;
    private javax.swing.JTextField NumberField1;
    private javax.swing.JTextField NumberField2;
    private javax.swing.ButtonGroup Operations;
    private javax.swing.JTextArea OutputArea;
    private javax.swing.JButton SolveOperationButton;
    private javax.swing.JRadioButton SubtractButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                           
}