/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @chongkuaile github.com
 */
public class BitwiseOperator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BitwiseOperator.class.getName());

    /**
     * Creates new form BitwiseOperator
     */
    public BitwiseOperator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InputField1 = new javax.swing.JTextField();
        InputField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BitwiseGatesComboBox = new javax.swing.JComboBox<>();
        BitsComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputArea = new javax.swing.JTextArea();
        GoButton = new javax.swing.JButton();
        OutputArea.setFont(new java.awt.Font(java.awt.Font.MONOSPACED, java.awt.Font.PLAIN, 13));
        setTitle("Bitwise Operator");
        setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputField1.addActionListener(this::InputField1ActionPerformed);

        jLabel1.setText("Enter number/s:");

        jLabel2.setText("Enter number/s:");

        BitwiseGatesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOT", "AND", "OR", "XOR", "SHL <<", "SHR >>" }));

        BitsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 bit", "16 bit" }));

        jLabel3.setText("Bits:");

        OutputArea.setColumns(20);
        OutputArea.setRows(5);
        jScrollPane1.setViewportView(OutputArea);

        GoButton.setText("Go");
        GoButton.addActionListener(this::GoButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(GoButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BitwiseGatesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BitsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(InputField1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputField2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BitwiseGatesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BitsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(GoButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

private void InputField1ActionPerformed(java.awt.event.ActionEvent evt) {
    GoButtonActionPerformed(evt);
}

private void GoButtonActionPerformed(java.awt.event.ActionEvent evt) {
    String operation = (String) BitwiseGatesComboBox.getSelectedItem();
    int bits = BitsComboBox.getSelectedIndex() == 0 ? 8 : 16;
    int mask = (1 << bits) - 1;          // 8 bit -> 255, 16 bit -> 65535

    try {
        int a = readNumber(InputField1, "first number", bits, mask);
        String result;

        switch (operation) {
            case "NOT": {
                int r = ~a & mask;
                result = "Operation: NOT (" + bits + "-bit)\n\n"
                        + "     " + toBinary(a, bits) + "   (" + a + ")\n"
                        + "NOT  " + "-".repeat(bits) + "\n"
                        + "  =  " + toBinary(r, bits) + "   (" + r + ")\n";
                result += summary(r, bits);
                break;
            }
            case "AND":
            case "OR":
            case "XOR": {
                int b = readNumber(InputField2, "second number", bits, mask);
                int r;
                if (operation.equals("AND")) {
                    r = a & b;
                } else if (operation.equals("OR")) {
                    r = a | b;
                } else {
                    r = a ^ b;
                }
                String sym = String.format("%-4s", operation);
                result = "Operation: " + operation + " (" + bits + "-bit)\n\n"
                        + "     " + toBinary(a, bits) + "   (" + a + ")\n"
                        + sym + " " + toBinary(b, bits) + "   (" + b + ")\n"
                        + "     " + "-".repeat(bits) + "\n"
                        + "  =  " + toBinary(r, bits) + "   (" + r + ")\n";
                result += summary(r, bits);
                break;
            }
            case "SHL <<":
            case "SHR >>": {
                int shift = readShift(InputField2, bits);
                boolean left = operation.startsWith("SHL");
                int r = left ? (a << shift) & mask : (a >>> shift) & mask;
                String sym = left ? "<<" : ">>";
                result = "Operation: " + operation + " (" + bits + "-bit)\n\n"
                        + "     " + toBinary(a, bits) + "   (" + a + ")\n"
                        + String.format("%-4s %d", sym, shift) + "\n"
                        + "     " + "-".repeat(bits) + "\n"
                        + "  =  " + toBinary(r, bits) + "   (" + r + ")\n";
                result += summary(r, bits);
                break;
            }
            default:
                result = "Unknown operation.";
        }

        OutputArea.setText(result);
        OutputArea.setCaretPosition(0);
    } catch (IllegalArgumentException ex) {
        OutputArea.setText("Error: " + ex.getMessage());
    }
}

    private int readNumber(javax.swing.JTextField field, String name, int bits, int mask) {
        String text = field.getText().trim().replace("_", "").replace(" ", "");
        if (text.isEmpty()) {
            throw new IllegalArgumentException("Please enter the " + name + ".");
        }
        int value;
        try {
            String lower = text.toLowerCase();
            if (lower.startsWith("0b")) {
                value = Integer.parseInt(text.substring(2), 2);
            } else if (lower.startsWith("0x")) {
                value = Integer.parseInt(text.substring(2), 16);
            } else {
                value = Integer.parseInt(text);
            }
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("\"" + field.getText().trim() + "\" is not a valid "
                    + name + ".\nUse decimal (12), binary (0b1100) or hex (0xC).");
        }
        if (value < 0 || value > mask) {
            throw new IllegalArgumentException("The " + name + " must be between 0 and " + mask
                    + " for " + bits + "-bit.");
        }
        return value;
    }

    private int readShift(javax.swing.JTextField field, int bits) {
        String text = field.getText().trim();
        if (text.isEmpty()) {
            throw new IllegalArgumentException("Please enter the shift amount in the second field.");
        }
        int shift;
        try {
            shift = Integer.parseInt(text);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Shift amount must be a whole number.");
        }
        if (shift < 0 || shift > bits) {
            throw new IllegalArgumentException("Shift amount must be between 0 and " + bits + ".");
        }
        return shift;
    }

    private String toBinary(int value, int bits) {
        String bin = Integer.toBinaryString(value);
        return "0".repeat(Math.max(0, bits - bin.length())) + bin;
    }

    private String summary(int r, int bits) {
        return "\nResult:\n"
                + "  Binary : " + toBinary(r, bits) + "\n"
                + "  Decimal: " + r + "\n"
                // \u2088 = subscript 8, \u2081\u2086 = subscript 16
                + "  Octal  : (" + Integer.toOctalString(r) + ")\u2088\n"
                + "  Hex    : (" + String.format("%0" + (bits / 4) + "X", r) + ")\u2081\u2086\n";
    }

                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BitwiseOperator().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> BitsComboBox;
    private javax.swing.JComboBox<String> BitwiseGatesComboBox;
    private javax.swing.JButton GoButton;
    private javax.swing.JTextField InputField1;
    private javax.swing.JTextField InputField2;
    private javax.swing.JTextArea OutputArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
